### ISSUE TITLE
How to use samples with Android Studio?

### ISSUE THREAD

**Issue by richardeakin** [libpd/pd-for-android#11]
Just briefly tried running `PdTest` in Android Studio (1.2.2) by importing the project from ADT and got the following error message:

```
Error:The project is using an unsupported version of Gradle.
```

Does anyone know if it is possible to use Android Studio and how, or must I still use Eclpse ADT?

Thanks!

**Comment by tkirshboim** [comment]
Hi!
@joebowbeer and I prepared pd-for-android for Android Studio and updated the gradle build files.
There's [an open pull request](https://github.com/libpd/pd-for-android/pull/10) for this and [some discussion](https://github.com/libpd/pd-for-android/issues/9). You can clone [the gradle_mods branch](https://github.com/joebowbeer/pd-for-android/tree/gradle_mods) from @joebowbeer's repo and build a .aar file of pd-for-android from the command line (s. the Readme on that branch).
This should works [Android Studio from version 1.3](http://tools.android.com/download/studio/canary/1-3-beta) onwards which supports NDK integration.

**Comment by tkirshboim** [comment]
Hi @richardeakin - Did this solve the problem for you?
