### ISSUE TITLE
Unable to install submodules and dependencies

### ISSUE THREAD

**Issue by mattgr0619** [libpd/pd-for-android#116]
Hi All,

I'm trying to create an android app with libpd, and attempted to clone the git repository in terminal. This step went fine, but when I tried installing the dependencies and submodules,
<br>
`git submodule sync --recursive`
<br>
`git submodule update --init --recursive`
<br>

...nothing happened, and so I dont think I was able to set up correctly. Keep in mind that I am following [this link](https://www.youtube.com/watch?v=uYQ8VhOZ9Vg) to set up with android studio, and so there may be some discrepancies in version of software.
<br>
Let me know if there is any step I am missing.
<br>
Thanks,
<br>
Matt

**Comment by joebowbeer** [comment]
Check the comments on that 5 year old video: it is obsolete.

The lib is now published and can be included as an external dependency. Most users will not need to build it.

See instructions for adding dependency in the project README.

By the way, our GitHub Action is building this library, though not in Android Studio.

Let us know if you continue to have problems.
