### ISSUE TITLE
The unauthenticated git protocol on port 9418 is no longer supported

### ISSUE THREAD

**Issue by funkyfourier** [libpd/pd-for-android#118]
When I do as it says in the README: `git submodule update --init --recursive` I get this:

```
Cloning into '/home/---/pd-for-android/PdCore/src/main/jni/libpd'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
According to [another issue](https://github.com/jazzband/pip-tools/issues/1522) I found regarding this, swapping out `git://` with `https://` is the recommended solution. I did so in `.git/config` and `.git/modules/PdCore/src/main/jni/libpd/config` and it seems to have worked.

**Comment by joebowbeer** [comment]
We need to change to https in .gitmodules and then update our link to libpd in order to pickup the change there
