### ISSUE TITLE
Unknown host CPU architecture: arm64

### ISSUE THREAD

**Issue by FunkyMuse** [libpd/pd-for-android#119]
Hey,

Many kudos for your hard work putting all of this together.

I'm currently encountering the following problem:
```
Unknown host CPU architecture: arm64
```
I'm trying to build the sample using **Mac M1 Pro** but it seems that architecture is not yet available for the library to be built upon, I can't run the samples.

**Comment by robertesler** [comment]
Hi FunkyMuse,  
Are you trying to run libpd in the Simulator or on an iOS device?  It should run on any modern device as arm64, but I haven't yet figured out a way to build it to run on the simulator successfully.

**Comment by FunkyMuse** [comment]
> Hi FunkyMuse, Are you trying to run libpd in the Simulator or on an iOS device? It should run on any modern device as arm64, but I haven't yet figured out a way to build it to run on the simulator successfully.

Android studio, physical device, Poco F3

**Comment by robertesler** [comment]
Sorry, my head was still in iOS bugs.  It's probably an issue with ndk-build and the M1 chips. Have you tried this solution? https://stackoverflow.com/questions/70752561/unknown-host-cpu-architecture-arm64-2022-macbook-air-m1

**Comment by FunkyMuse** [comment]
> Sorry, my head was still in iOS bugs. It's probably an issue with ndk-build and the M1 chips. Have you tried this solution? https://stackoverflow.com/questions/70752561/unknown-host-cpu-architecture-arm64-2022-macbook-air-m1

Thanks, didn't know about this, fixed it using this solution, then i ran into this https://github.com/libpd/pd-for-android/issues/118 and gladly there was an answer too.
