### ISSUE TITLE
libpd crash on compileSdkVersion 23 with java.lang.UnsatisfiedLinkError: 

### ISSUE THREAD

**Issue by chrisgradl** [libpd/pd-for-android#13]
When setting the targetsdk to API Level 23 libpd crash

java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/sonigaitandroid-2/lib/arm/libpd.so: has text relocations

In previous Android Versions this was only a warning but it changed in the latest release

**Comment by tkirshboim** [comment]
Hi,
Can you explain a bit more how the crash happens? Are you using the latest version of pd-for-android (the current master branch)?
Using the current version, I changed the targetsdk API level of the PdTest app to 23, compiled it and ran it on a API level 23 emulator and it worked fine.

**Comment by devdev-dev** [comment]
Same problem here. Updating the SDK API Level to 23 in Android Studio causes a crash as follows:
 
```java
11-02 14:36:05.342 8448-8448/? E/AndroidRuntime: FATAL EXCEPTION: main
11-02 14:36:05.342 8448-8448/? E/AndroidRuntime: Process: com.deviantdev.libpd, PID: 8448
11-02 14:36:05.342 8448-8448/? E/AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.deviantdev.libpd-1/lib/arm/libpd.so: has text relocations
11-02 14:36:05.342 8448-8448/? E/AndroidRuntime: at java.lang.Runtime.loadLibrary(Runtime.java:372)
11-02 14:36:05.342 8448-8448/? E/AndroidRuntime: at java.lang.System.loadLibrary(System.java:1076)
11-02 14:36:05.342 8448-8448/? E/AndroidRuntime: at org.puredata.core.PdBase.<clinit>(PdBase.java:55)
11-02 14:36:05.342 8448-8448/? E/AndroidRuntime: at org.puredata.android.io.PdAudio.isRunning(PdAudio.java:122)
11-02 14:36:05.342 8448-8448/? E/AndroidRuntime: at org.puredata.android.io.PdAudio.initAudio(PdAudio.java:57)
```

**Comment by tkirshboim** [comment]
Hi @devdev-dev Are you using the latest version of pd-for-android (the current master branch)?

**Comment by tkirshboim** [comment]
Hi @devdev-dev ! Could you please explain how you're getting this crash so I could try and reproduce it?

**Comment by luizmello** [comment]
Hi I have erros when set the compileSdkVersion to 23 in PdCore and AndroiMidi modules.

First error is:
Error:(20, 23) error: package org.apache.http does not exist
...

I found this solution: 
add this line to build.gradle (AndroidMidi) :  useLibrary 'org.apache.http.legacy'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"
    useLibrary 'org.apache.http.legacy'
...
    }


Second error : 
Error:(252, 16) error: cannot find symbol method setLatestEventInfo(PdService,String,String,PendingIntent)

		@SuppressWarnings("deprecation")
		protected Notification makeNotification(Intent intent, int icon, String title, String description)   {
			PendingIntent pi = PendingIntent.getActivity(getApplicationContext(), 0, intent, 0);
			Notification notification = new Notification(icon, title, System.currentTimeMillis());
			notification.setLatestEventInfo(PdService.this, title, description, pi);
			notification.flags |= Notification.FLAG_ONGOING_EVENT;
			return notification;
		}

I try to fix it with the new Notification.Builder (http://developer.android.com/reference/android/app/Notification.Builder.html)
but without success.

Can I use these modules to the SDK API 23?
Is there any problem if I continue using the API 22 for the modules and the API 23 for the app?
Thank you for your attention
