### ISSUE TITLE
ARM64 support?

### ISSUE THREAD

**Issue by rayalu** [libpd/pd-for-android#14]
Is the support for arm64 in the pipeline?

**Comment by tkirshboim** [comment]
If you add ```arm64-v8a``` to list of ABIs in the [Application.mk](https://github.com/libpd/pd-for-android/blob/master/PdCore/jni/Application.mk#L2) it will build it. I don't have an arm64 to test it with, but the build with NDK went fine with it.
You can pull [this fork](https://github.com/tkirshboim/pd-for-android) if you want to try it out with Android Studio until [this pull request](https://github.com/libpd/pd-for-android/pull/10) is merged.
