### ISSUE TITLE
errors when set the compileSdkVersion to 23 in PdCore and AndroiMidi modules

### ISSUE THREAD

**Issue by luizmello** [libpd/pd-for-android#15]
Hi I have errors when set the compileSdkVersion to 23 in PdCore and AndroiMidi modules.

First error is:
Error:(20, 23) error: package org.apache.http does not exist
...

I found this solution: 
add this line to build.gradle (AndroidMidi) :  useLibrary 'org.apache.http.legacy'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"
    useLibrary 'org.apache.http.legacy'
...
    }

Second error : 
Error:(252, 16) error: cannot find symbol method setLatestEventInfo(PdService,String,String,PendingIntent)

		@SuppressWarnings("deprecation")
		protected Notification makeNotification(Intent intent, int icon, String title, String description)   {
			PendingIntent pi = PendingIntent.getActivity(getApplicationContext(), 0, intent, 0);
			Notification notification = new Notification(icon, title, System.currentTimeMillis());
			notification.setLatestEventInfo(PdService.this, title, description, pi);
			notification.flags |= Notification.FLAG_ONGOING_EVENT;
			return notification;
		}

I try to fix it with the new Notification.Builder (http://developer.android.com/reference/android/app/Notification.Builder.html)
but without success.

Can I use these modules to the SDK API 23?
Is there any problem if I continue using the API 22 for the modules and the API 23 for the app?
Thank you for your attention

**Comment by tkirshboim** [comment]
Hi!

Android supports MIDI from API level 23 with the (android.media.midi)[http://developer.android.com/reference/android/media/midi/package-summary.html] package.
I fixed the issue in the pd-for-android code so that it now compiles to this API level. See #16 

>Can I use these modules to the SDK API 23?
Yes, you can use these modules and target API level 23 in your app.

> Is there any problem if I continue using the API 22 for the modules and the API 23 for the app?
I think this should be fine.

**Comment by luizmello** [comment]
Hello, thank you for your attention.
I successfully compile the PdCore file (.aar) 
and now I'm using it directly, no longer need to import as modules on the Android Studio.
Also did a quick test and it worked well targeting SDK API 23.

Thanks!

**Comment by tkirshboim** [comment]
Glad to hear that!
