### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by joebowbeer** [libpd/pd-for-android#24]
The [Wiki](https://github.com/libpd/pd-for-android/wiki) needs to update. In particular, the [Android development with Eclipse](https://github.com/libpd/pd-for-android/wiki/eclipse) page should be removed and an Android Studio page should be added if needed.

**Comment by tkirshboim** [comment]
Added deprecation notice to [Eclipse Wiki page](https://github.com/libpd/pd-for-android/wiki/eclipse)

**Comment by tkirshboim** [comment]
I suggest closing this issue once #25 is merged, as that pull request updated the Readme with the current usage of the library.

**Comment by joebowbeer** [comment]
We should also update the Wiki's [Home](https://github.com/libpd/pd-for-android/wiki) page, which is currently mostly obsolete.

**Comment by joebowbeer** [comment]
I updated the Wiki home page.
