### ISSUE TITLE
Add Proguard Rules to Wiki and Sample Apps

### ISSUE THREAD

**Issue by luizmello** [libpd/pd-for-android#35]
Hi, I was having a problem when I tried to create an signed APK with "minifyEnabled true" when using pd-for-android directly as a dependency in the file "app>build.gradle".
Sometimes the release don't compiles and sometimes compiles but crash on app start.

This is the way I'm doing:
```
dependencies {
    ...
    ...
    compile 'org.puredata.android:pd-core:1.0.0-rc4'
}
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```
I've solved the problem with the following procedure:
In proguard-rules.pro file, insert the following line to skip class regarding the PureData:
```
-keep class org.puredata.** { *; }
```

Using this my app.apk size reduced from 3.5Mb to 2.5Mb.

This is the correct way to do this? Anyone have the same problem?

Sorry if here isn't the right place to post this. But I take a lot o time to handle this and I want to contribute with this great project.
Thank you

**Comment by joebowbeer** [comment]
That rule would be the conservative way to make sure all the puredata classes are retained.

The default rules provided by the Android SDK will try to identify and retain methods that may be called from native code, but they are not perfect.

We should add this proguard rule to the wiki, and also to our sample apps.

**Comment by luizmello** [comment]
Hi @joebowbeer , thanks for your feedback. I hope this helps other users.

**Comment by tkirshboim** [comment]
Hi @luizmello . Thanks for the reporting this and offering the solution. I'm reopening this issue until this is added to the documentation and to the sample apps like @joebowbeer suggested.

**Comment by joebowbeer** [comment]
I added a [Proguard](https://github.com/libpd/pd-for-android/wiki/Proguard) page to the wiki
