### ISSUE TITLE
Add print concatenation

### ISSUE THREAD

**Issue by danomatika** [libpd/pd-for-android#38]
Looks like libpd in pd-for-android is not being built with the extras externals, judging from this issue: https://github.com/libpd/libpd/issues/112

This means expr, expr~, & fexpr~ aren't available as well as sigmund~, bob~, etc.

Also, I'd suggest adding the print concatenation layer so prints are grouped per line as opposed to the per word default: https://github.com/libpd/libpd/blob/master/libpd_wrapper/util/z_print_util.h

**Comment by tkirshboim** [comment]
@danomatika I've just tested this and it seems to me that all of these objects that you mentioned are included except for bob~ , so I don't think that this is the issue with https://github.com/libpd/libpd/issues/112

This is what I used to test:
https://github.com/tkirshboim/pd-for-android-test

**Comment by danomatika** [comment]
If you want to test all the EXTRAS, add these to the list: bonk~, loop~, choice, lrshift~, pique, stdout

**Comment by danomatika** [comment]
Following this good idea, I added a test patch with all the extras objects to the c pdtest: https://github.com/libpd/libpd/commit/dca1c417789cdb559aa24751908950bb4964b8b0

This way we can double check the fault is not in the libpd c core.

**Comment by tkirshboim** [comment]
I added all the extra objects from the test patch on libpd. All of those extras can be created apart from bob~ and stdout
I don't know if this is something that was recently introduced or if those objects were included in the Android builds in the past. Will have to look into that.

**Comment by danomatika** [comment]
bob is new as of at least 6 months ago. Assuming the android build doesn't use the libpd makefile, I bet the build is just missing those c files.

**Comment by tkirshboim** [comment]
I see. So perhaps simply adding those extras to the https://github.com/libpd/libpd/blob/master/Android.mk will fix it. I'll give it a try.

**Comment by danomatika** [comment]
Yup, looks like those are missing from the .so build targets. Easy enough!
