### ISSUE TITLE
Needs expr~ attribution

### ISSUE THREAD

**Issue by joebowbeer** [libpd/pd-for-android#40]
expr is LGPL licensed and requires attribution. Apps built with pd-for-android should include expr in their list of copyrights.

The pd-for-android release should make this clear. (In its Readme and Licenses?)

See question raised here: https://github.com/libpd/pd-for-android/pull/39

**Comment by nettoyeurny** [comment]
Hmm, I thought the expr license issue had been resolved:
https://www.mail-archive.com/pd-list@lists.iem.at/msg05116.html


I don't see it in the Pd repository at github, though, but maybe the new
license is upstream somewhere? In any case, I think we should find the
updated version of expr and distribute that with libpd.

**Comment by joebowbeer** [comment]
Thanks for the update Peter. We should make the licensing clearer to avoid more confusion.

**Comment by danomatika** [comment]
As of Pd 0.47, expr is now BSD and included with the PD sources. This issue is no longer needed.
