### ISSUE TITLE
gradle build not finding support libraries

### ISSUE THREAD

**Issue by monkeyswarm** [libpd/pd-for-android#41]
When I run
`./gradlew PdCore:assembleRelease`
I get:

> A problem occurred configuring project ':CircleOfFifths'.
> A problem occurred configuring project ':PdCore'.
   > Could not resolve all dependencies for configuration ':PdCore:_debugCompile'.
      > Could not find com.android.support:support-v4:23.1.0.
        Searched in the following locations:
            https://jcenter.bintray.com/com/android/support/support-v4/23.1.0/support-v4-23.1.0.pom
            https://jcenter.bintray.com/com/android/support/support-v4/23.1.0/support-v4-23.1.0.jar
            file:/Users/diglesia/android-sdks/extras/google/m2repository/com/android/support/support-v4/23.1.0/support-v4-23.1.0.pom
            file:/Users/diglesia/android-sdks/extras/google/m2repository/com/android/support/support-v4/23.1.0/support-v4-23.1.0.jar
        Required by:
            org.puredata.android:PdCore:1.0.0

 See attached image for the state of my android-sdks folder. The support libraries, as installed by current Android Studio SDK, are in 
android-sdks/extras/android/support
(wheras android-sdks/extras/google/m2repository/com/android/support is empty)

Please advise! Thanks  

![screen shot 2016-01-31 at 12 27 06 pm](https://cloud.githubusercontent.com/assets/1235083/12704765/c70b6516-c816-11e5-8777-4dc04a60099b.png)

**Comment by joebowbeer** [comment]
Those artifacts come from Android Support Repository (m2repository/com/android/support). Make sure it is up to date in the SDK Manager.

http://stackoverflow.com/a/32280940/901597

**Comment by monkeyswarm** [comment]
Thanks for the tip...
