### ISSUE TITLE
Add reference for API 23 permissions handling

### ISSUE THREAD

**Issue by caltivan** [libpd/pd-for-android#43]
Hi
I have the next issue on Android 6.0 when is trying to run the app with libpd, as far as i know the support required to compile the libpd with the latest NDK to avoid the text relocation

 E/AndroidRuntime(19967): java.lang.UnsatisfiedLinkError: dlopen failed: /lib/arm/libpd.so: has text relocations

**Comment by tkirshboim** [comment]
Hi @caltivan 
This seems to be related to the issue mentioned here:
https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-runtime

Does lowering the targetSdkVersion of your app to 22 fix this issue?

**Comment by caltivan** [comment]
Yes that solved it temporarily but the problem is that my app was uploaded for 23  in the store and there's no way back to put it again in 22, o i have to figure out how to solve it for 23

**Comment by tkirshboim** [comment]
I see.. Sorry to hear that. We will try to add support for Android API level 23 soon, for now I'll update the documentation so that it's clear that apps should not target API level 23 or above.

**Comment by caltivan** [comment]
Thank you i will appreciate a lot if you are able to update it.

**Comment by joebowbeer** [comment]
@tkirshboim which NDK version built the released .aar?

I rebuilt with NDK r10e (latest) and I don't see any warnings regarding text relocations. Even if I change all the sample app's targetSdkVersion to 23, they install without problem, and they run fine except for the permissions-related issues.

**Comment by tkirshboim** [comment]
@joebowbeer I've used this version of the NDK as well, however I haven't tested it with a API level 23 device. 

@caltivan are you using the pre built library version from jcenter or are you building it yourself?

**Comment by giovanymoreno** [comment]
Yes im using the prebuilt version, as far as i know the solution should be to compile with the lates NDK but im no sure how to do it, do you have any guideline or tutorial page to follow?

**Comment by caltivan** [comment]
Yes im using the prebuilt version, as far as i know the solution should be to compile with the lates NDK but im no sure how to do it, do you have any guideline or tutorial page to follow?

**Comment by joebowbeer** [comment]
@tkirshboim CircleCI has verified that their installed NDK is r10d, however I don't know if r10e is required to solve this problem.

@caltivan It's odd that the path in the error message contains 'arm' and not armeabi-v7a. What device model was used?

**Comment by joebowbeer** [comment]
As far as I know, the released PdCore is already compatible with API 23, and was built for API 23.

Apparently, ``readelf`` can be used to reveal text relocations, but I just checked all of the released .so files for all architectures, and turned up nothing.

For example:

```
$ cd android-ndk-r10e\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\bin
$ arm-linux-androideabi-readelf.exe -d -r path-to-pd-core\jni\armeabi\libpd.so | grep TEXT
```

**Comment by tkirshboim** [comment]
I can confirm that I could not reproduce this issue on a API 23 arm emulator with the prebuilt version.

**Comment by mlennon3** [comment]
I cannot get my app to record on marshmallow, so I tried the PdTest and ScenePlayer apps and they don't seem to access the microphone..

PdTest has no output for the 'patch mic to both channels'
ScenePlayer, when playing back a recording, will have no sounds recorded

The apps also don't ask for permission when running them.

**Comment by joebowbeer** [comment]
@mlennon3 Are you referring to custom versions of PdTest and ScenePlayer built for API 23? Their targetSdkVersion is currently 22, and so there should not be an issue with the RECORD_AUDIO permission -- unless you manually revoke that permission in the app settings.

Apps targeting API 23 are required to ask permission to access the microphone, but the additional code has not yet been added to any of the pd-for-android samples:

[developer.android.com/training/permissions](http://developer.android.com/training/permissions/index.html)

[inthecheesefactory.com/blog](http://inthecheesefactory.com/blog/things-you-need-to-know-about-android-m-permission-developer-edition/en)

**Comment by mlennon3** [comment]
No, I re-cloned the project so that it was fresh and made sure to install using the readme directions.
When I run the PdTest and press play to start recording, I get an error:

```02-18 11:18:19.282 30245-30245/org.puredata.android.test E/AudioRecord: start() status -38```

I have checked and Android App permissions has given permission to PdTest to use the microphone

**Comment by tkirshboim** [comment]
@mlennon3 Thanks for letting us know. We should add this issue to the documentation as well.

**Comment by markos14** [comment]
@mlennon3 
I'm trying to run a simple patch on a Nexus 4 api23 emulator in Android Studio

adc~   ->     *~ 0.5    ->    dac~

But I'm getting no microphone input signal. I presume it is a similar issue as yours. 
I'm new to Android Studio and am unsure how to add permissions for my PD patch. As seen in the picture, I have not requested any permissions. Do I do so like I would request to use the Record_Audio function <uses-permission android:name="android.permission.RECORD_AUDIO"/>?

![capture](https://cloud.githubusercontent.com/assets/18605266/16896497/bc9daca2-4b8c-11e6-95a9-2e61092317c3.PNG)

**Comment by joebowbeer** [comment]
@markos14 
What is the targetSdkVersion of your HelloPD app?

Apps that target API 23 or higher are required to request permissions. This might be the problem. Apps targeting API 22 or lower are automatically granted permissions on installation. In case it's not clear, apps targeting API 22 can run on API 23 devices.

Requesting permissions in API 23+ is something that needs to be done in the app itself, not in the pd-for-android library. All of the sample apps currently target API 22.

**Comment by tkirshboim** [comment]
@markos14 aside from the point raised by @joebowbeer (try to target API 22) , it's also evident in the screenshot that your app has not requested any permissions. You can have a look at the permission declarations in the test app as a reference:

https://github.com/libpd/pd-for-android/blob/master/PdTest/AndroidManifest.xml

You need to declare `<uses-permission android:name="android.permission.RECORD_AUDIO" />` for your app to have access to the microphone.

**Comment by markos14** [comment]
Changed the targetsdkversion to 22 (left the compilesdkversion at 23), added microphone permission.. 
Now all works fine!Thanks a mil..

There is nearly a second of latency for the audio to go from the built-in microphone to the earphones. Is that expected? Or is that due to my laptop specs which aren't great?

![capture](https://cloud.githubusercontent.com/assets/18605266/16901491/b43224c4-4c3d-11e6-860b-12a9be7659ae.PNG)
