### ISSUE TITLE
error: ... couldn't create

### ISSUE THREAD

**Issue by mlennon3** [libpd/pd-for-android#46]
I'm trying to get a log printed of the tone of a signal played, so I am using the PdTest with a small diff to listen to the symbol 'pitch' and log it, and a small change to the .pd file to have the symbol sent [pd image here](http://imgur.com/Hee0gsz).

When I press the play button in PdTest I get this output:
```
8 12:16:15.479 26321-26321/org.puredata.android.test I/PdUiDispatcher: print:  
02-18 12:16:15.479 26321-26321/org.puredata.android.test I/PdUiDispatcher: print: bob~
02-18 12:16:15.479 26321-26321/org.puredata.android.test I/PdUiDispatcher: print: 
02-18 12:16:15.479 26321-26321/org.puredata.android.test I/PdUiDispatcher: print: error: ... couldn't create
02-18 12:16:15.479 26321-26321/org.puredata.android.test I/PdUiDispatcher: print: fiddle version 1.1 TEST4
02-18 12:16:15.479 26321-26321/org.puredata.android.test I/PdUiDispatcher: print: bonk version 1.5
02-18 12:16:15.479 26321-26321/org.puredata.android.test I/PdUiDispatcher: print: pique 0.1 for PD version 23
02-18 12:16:15.479 26321-26321/org.puredata.android.test I/PdUiDispatcher: print: 
02-18 12:16:15.479 26321-26321/org.puredata.android.test I/PdUiDispatcher: print:  
02-18 12:16:15.479 26321-26321/org.puredata.android.test I/PdUiDispatcher: print: stdout
02-18 12:16:15.479 26321-26321/org.puredata.android.test I/PdUiDispatcher: print: 
02-18 12:16:15.479 26321-26321/org.puredata.android.test I/PdUiDispatcher: print: error: ... couldn't create
02-18 12:16:15.479 26321-26321/org.puredata.android.test I/PdUiDispatcher: print: PD_RUNS: 29.186
```
and my logs aren't printed.

I'm running it through AndroidStudio, on OSX 10.11.2 and on a HTC One m8 running Marshmallow.

**Comment by tkirshboim** [comment]
Hi @mlennon3 ! Are you using the the library from JCenter? That version doesn't include some objects (like bob~) that we recently added to pd-for-android .

**Comment by mlennon3** [comment]
I'm 95% sure I was using the version given in this repo, I didn't have any changes in the build.gradle.

I can't test and make sure today tho, dont have my phone

**Comment by alexgomes09** [comment]
was this problem solved? I am still seeing this error.  I am trying load a pre-built  shared m4aPlayer library, that I've in my libs folder and I also pointed from build.gradle - 

`sourceSets {
        main {
            jniLibs.srcDir 'libs'
            jni.srcDirs = []
        }
    }`

Tried so many ways to load it, but failing every-time I read the patch file(which requires m4aPlayer).
Also tried System.loadLibrary("m4aPlayer"), but failed on that too. After a clean build I can see that libm4aPlayer.so does get copied along with other libpd.so to data/data/package-name/lib. But there is no sound/audio being played from pd. All the pd command does go through 

I am using `compile 'org.puredata.android:pd-core:1.0.1'`

[http://stackoverflow.com/questions/37535827/android-libpd-not-working-not-making-any-audio](url)

**Comment by tkirshboim** [comment]
@mlennon3 I assume that since you didn't reply that the issue was solved for you? I'm closing this issue, but feel free to reopen if this issue persists.

@alexgomes09 The issue you're reporting seems to a different one. Please open a separate issue for it and provide a snippet of the patch / code example that shows the problem. Without an example it's difficult to help with the troubleshooting.

**Comment by mlennon3** [comment]
@tkirshboim yes I figured it out, sadly I don't remember what did it!  Fair to close, thanks
