### ISSUE TITLE
[midiin] only shows data when calling PdBase:sendMidiByte

### ISSUE THREAD

**Issue by monkeyswarm** [libpd/pd-for-android#48]
On other platforms (native PureData on OSX, libpd on iOS), all incoming midi data (noteon/off, ctrl, etc) into the patch is reflected out the [midiin] object. On Android, however, the object does not output any data.

**Comment by tkirshboim** [comment]
I could reproduce this as well.
`midiin` only receives data when I use the java call `PdBase:sendMidiByte`. When I use `PdBase:sendNoteOn` then 'notein' gets the data. So while the data does get through to the patch, this is inconsistent with the other PD ports, as you mention, in which `midiin` functions as an "omni-in". I don't know the reason for this difference in behavior on the Android port. Pinging @nettoyeurny here .. 😉  
If this for some reason can't be changed, we should at least mention this in the documentation.

**Comment by tkirshboim** [comment]
@monkeyswarm I realize now that this is rather an issue of missing documentation than a bug in the library. See the following discussion:
https://github.com/libpd/libpd/issues/133

**Comment by tkirshboim** [comment]
Added the missing documentation to the [libpd wiki](https://github.com/libpd/libpd/wiki/libpd#difference-in-midiin-functionality-compared-to-pd-vanilla).
