### ISSUE TITLE
Could you please clarify licensing requirements

### ISSUE THREAD

**Issue by showlabor** [libpd/pd-for-android#68]
Hi,
I'm about to release a small Android app which uses pd-for-android. The simplicity of using it today via JCenter is a bless compared to when I first used it backin the Eclipse days. Thanks for that!

I'm struggling a bit with correctly citing the license in the app. Since I'm including PdCore from JCenter I've started by citing https://github.com/libpd/pd-for-android/blob/master/PdCore/LICENSE.txt. Is that already enough or should I cite libpd's LICENSE.txt ( https://github.com/libpd/libpd/blob/master/LICENSE.txt ) as well, which BTW reads a bit different w.r.t. copyright than the copyright information in libpd's README.md ( https://github.com/libpd/libpd/blob/master/README.md ).

Thanks in advance,
Felix

**Comment by joebowbeer** [comment]
The license for the jCenter artifact is described as **New BSD**:

https://bintray.com/pd-for-android/maven/pd-for-android

and contains three conditions.

The license text published to JCenter is from the pd-for-android repo, but the one in libpd is essentially identical. Both list the same conditions, and indicate that several individuals hold copyrights on the source files.
