### ISSUE TITLE
Wheezes when try to play two sounds at the same time

### ISSUE THREAD

**Issue by evabishchevich** [libpd/pd-for-android#73]
I have two receivers in pd file. Both of them play different wav files. When I send bang (PdBase.sendBang("...")) to the first receiver, and while it's playing wav file I send bang to the second receiver I get wheezes. Looks like sound overloading when libpd plays 2 sound at the same time. 
I've tested on Nexus 5X (Android O), Nexus 6P (Android N), Galaxy J7 2016 (Android M)

**Comment by evabishchevich** [comment]
That was a problem with my output signal on Android. This signal was too loud and because of that I've heard some wheezes

**Comment by rpattabi** [comment]
Thanks for the update. I have also noticed weird output few times only to find that the phone's speakers were obstructed, changes in the obstruction caused audio distortion. So no problem with pd-for-android in such cases.
