### ISSUE TITLE
armeabi deprecated

### ISSUE THREAD

**Issue by F-Schlatt** [libpd/pd-for-android#78]
Under PdCore -> jni -> Application.mk, 
`APP_ABI := armeabi armeabi-v7a x86` needs to be changed to `APP_ABI := armeabi-v7a x86`
as armeabi is deprecated and the ndk build of PdCore will fail with exit status 2.

**Comment by tkirshboim** [comment]
Fixed by https://github.com/libpd/pd-for-android/pull/70
